# -*- coding: utf-8 -*-
import json, os, sys

# Fix Windows console encoding
if sys.platform == 'win32':
    os.environ['PYTHONIOENCODING'] = 'utf-8'

# Use raw path from os to handle Turkish chars
BASE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(BASE, "project-08.json")

with open(OUT, "r", encoding="utf-8") as f:
    data = json.load(f)

m2 = {
  "id": "m2",
  "title": "Core Chatbot with Context & Memory",
  "estimated_days": 2,
  "must_note": [
    "LangChain'de memory 3 t\u00fcrd\u00fcr: BufferMemory (t\u00fcm mesajlar\u0131 tutar), SummaryMemory (\u00f6zetler), WindowMemory (son N mesaj). Production'da genellikle hybrid kullan\u0131l\u0131r.",
    "System prompt, agent'\u0131n 'ki\u015fili\u011fini' belirler. \u00c7ok uzun system prompt = yava\u015f + pahal\u0131. \u00c7ok k\u0131sa = tutars\u0131z davran\u0131\u015f. Dengeyi bul.",
    "ChatPromptTemplate'te variable'lar {curly_braces} ile tan\u0131mlan\u0131r. Her variable runtime'da doldurulur.",
    "Redis-backed memory, server restart'lar\u0131nda konu\u015fma ge\u00e7mi\u015fini korur. In-memory dict ile bu m\u00fcmk\u00fcn de\u011fil."
  ],
  "senior_learns": "Senior m\u00fchendis, memory stratejisini konu\u015fma uzunlu\u011funa ve maliyete g\u00f6re se\u00e7er. K\u0131sa konu\u015fmalar (5-10 mesaj) i\u00e7in BufferMemory yeterlidir. Uzun konu\u015fmalarda (20+ mesaj) SummaryMemory ile eski mesajlar\u0131 \u00f6zetleyip token tasarrufu sa\u011flar. Ayr\u0131ca Redis'teki TTL de\u011ferini business requirement'a g\u00f6re ayarlar \u2014 m\u00fc\u015fteri 30 dakika sonra geri d\u00f6nerse \u00f6nceki konu\u015fmadan devam edebilmeli mi? Bu karar memory tasar\u0131m\u0131n\u0131 do\u011frudan etkiler.",
  "steps": [
    {
      "title": "LLM ile \u0130lk Agent'\u0131 Olu\u015ftur (FAQ Agent)",
      "why": "Placeholder fonksiyonlar\u0131 ger\u00e7ek LLM \u00e7a\u011fr\u0131lar\u0131yla de\u011fi\u015ftirme zaman\u0131. FAQ Agent en basit agent oldu\u011fu i\u00e7in onunla ba\u015fl\u0131yoruz \u2014 sadece system prompt ve LLM yan\u0131t\u0131, hen\u00fcz tool yok.",
      "instructions": "ChatOpenAI ile LLM instance'\u0131 olu\u015ftur. ChatPromptTemplate ile FAQ agent'\u0131n system prompt'unu tan\u0131mla. Agent'\u0131 m\u00fc\u015fteri dostu, profesyonel ve T\u00fcrk\u00e7e yan\u0131t verecek \u015fekilde konf\u0131g\u00fcre et.",
      "code_snippet": "# agents/faq_agent.py\nfrom langchain_openai import ChatOpenAI\nfrom langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder\nfrom langchain_core.messages import AIMessage\nfrom config.settings import get_settings\nfrom graph.state import AgentState\n\nsettings = get_settings()\n\nllm = ChatOpenAI(\n    model=settings.openai_model,\n    temperature=settings.openai_temperature,\n    api_key=settings.openai_api_key\n)\n\nfaq_prompt = ChatPromptTemplate.from_messages([\n    (\"system\", \"\"\"Sen TechCorp sirketinin AI musteri destek asistanisin.\nGorevin: Sik sorulan sorulari yanitlamak.\n\nKurallar:\n- Her zaman Turkce yanit ver\n- Nazik ve profesyonel ol\n- Emin olmadigin konularda uzman yonlendirmesi oner\n- Yanitlarin kisa ve oz olsun (maks 3 paragraf)\n\nSirket bilgileri:\n- TechCorp: SaaS platform, proje yonetimi araci\n- Planlar: Free, Pro (99 TL/ay), Enterprise (ozel fiyat)\n- Destek saatleri: Hafta ici 09:00-18:00\n{context}\"\"\"),\n    MessagesPlaceholder(variable_name=\"messages\"),\n])\n\nasync def faq_node(state: AgentState) -> dict:\n    chain = faq_prompt | llm\n    response = await chain.ainvoke({\n        \"messages\": state[\"messages\"],\n        \"context\": \"\"  # M4'te RAG ile doldurulacak\n    })\n    return {\"messages\": [response], \"current_agent\": \"faq\"}",
      "deep_dive": "ChatPromptTemplate.from_messages bir liste al\u0131r \u2014 her eleman bir tuple: (role, content). 'system' rol\u00fc LLM'in davran\u0131\u015f\u0131n\u0131 belirler. MessagesPlaceholder, konu\u015fma ge\u00e7mi\u015fini template'e enjekte eder \u2014 multi-turn konu\u015fman\u0131n temelini olu\u015fturur. Pipe operat\u00f6r\u00fc (|) LangChain'in LCEL syntax'\u0131d\u0131r: prompt | llm ifadesi '\u00f6nce prompt'u olu\u015ftur, sonra LLM'e g\u00f6nder' anlam\u0131na gelir.",
      "checkpoint": "FAQ agent'a 'Planlar\u0131n\u0131z nelerdir?' diye sordu\u011funda T\u00fcrk\u00e7e, \u015firket bilgilerini i\u00e7eren bir yan\u0131t d\u00f6nmeli."
    },
    {
      "title": "Redis ile Conversation Memory Entegrasyonu",
      "why": "Chatbot'un \u00f6nceki mesajlar\u0131 'hat\u0131rlamas\u0131' gerekir \u2014 yoksa her mesaj yeni bir konu\u015fma gibi olur. Redis, memory'yi process d\u0131\u015f\u0131nda saklar. Server restart olsa bile konu\u015fma devam eder.",
      "instructions": "RedisChatMessageHistory ile session-based memory olu\u015ftur. Her session_id i\u00e7in ayr\u0131 konu\u015fma ge\u00e7mi\u015fi sakla. TTL ile eski session'lar\u0131 otomatik temizle.",
      "code_snippet": "# services/memory_service.py\nimport json\nfrom langchain_community.chat_message_histories import RedisChatMessageHistory\nfrom langchain_core.messages import BaseMessage, HumanMessage, AIMessage\nfrom config.settings import get_settings\nimport redis.asyncio as redis\n\nsettings = get_settings()\n\nclass ConversationMemory:\n    def __init__(self):\n        self.redis_client = redis.from_url(settings.redis_url)\n        self.ttl = settings.session_ttl_seconds\n    \n    def get_history(self, session_id: str) -> RedisChatMessageHistory:\n        return RedisChatMessageHistory(\n            session_id=session_id,\n            url=settings.redis_url,\n            ttl=self.ttl\n        )\n    \n    async def add_message(self, session_id: str, message: BaseMessage):\n        history = self.get_history(session_id)\n        history.add_message(message)\n    \n    async def get_messages(self, session_id: str, last_n: int = 20) -> list[BaseMessage]:\n        history = self.get_history(session_id)\n        messages = history.messages\n        return messages[-last_n:] if len(messages) > last_n else messages\n    \n    async def save_session_metadata(self, session_id: str, metadata: dict):\n        key = f\"session_meta:{session_id}\"\n        await self.redis_client.set(key, json.dumps(metadata, default=str), ex=self.ttl)\n    \n    async def get_session_metadata(self, session_id: str) -> dict | None:\n        key = f\"session_meta:{session_id}\"\n        data = await self.redis_client.get(key)\n        return json.loads(data) if data else None\n    \n    async def clear_session(self, session_id: str):\n        history = self.get_history(session_id)\n        history.clear()\n        await self.redis_client.delete(f\"session_meta:{session_id}\")\n\nmemory_service = ConversationMemory()",
      "deep_dive": "RedisChatMessageHistory, LangChain'in ChatMessageHistory interface'ini implement eder. Her mesaj Redis'te bir list (RPUSH) olarak saklan\u0131r. TTL parametresi Redis'in EXPIRE komutunu kullan\u0131r. last_n parametresi ile sliding window memory olu\u015fturuyoruz \u2014 20 mesajdan eski olanlar LLM'e g\u00f6nderilmez, token maliyetini kontrol alt\u0131nda tutar.",
      "checkpoint": "Bir session'a 5 mesaj ekleyip, get_messages ile son 3'\u00fcn\u00fc alabilmeli. Redis'te key'lerin olu\u015ftu\u011funu do\u011frulay\u0131n."
    },
    {
      "title": "LLM Tabanl\u0131 Router Agent",
      "why": "Keyword-based routing k\u0131r\u0131lgand\u0131r \u2014 'param nerede?' faturay\u0131 m\u0131 teknik sorunu mu soruyor? LLM tabanl\u0131 router, mesaj\u0131n anlam\u0131n\u0131 kavrayarak do\u011fru agent'a y\u00f6nlendirir.",
      "instructions": "Router agent'\u0131 LLM ile yeniden yaz. Structured output (JSON mode) kullanarak intent, confidence ve reasoning d\u00f6nd\u00fcr. Few-shot \u00f6rnekler ekle.",
      "code_snippet": "# agents/router_agent.py\nfrom langchain_openai import ChatOpenAI\nfrom langchain_core.prompts import ChatPromptTemplate\nfrom langchain_core.output_parsers import JsonOutputParser\nfrom pydantic import BaseModel, Field\nfrom graph.state import AgentState\nfrom config.settings import get_settings\n\nsettings = get_settings()\n\nclass RouterDecision(BaseModel):\n    intent: str = Field(description=\"Tespit edilen intent: faq, billing, tech_support\")\n    confidence: float = Field(description=\"Guven skoru 0-1 arasi\")\n    reasoning: str = Field(description=\"Routing kararinin kisa aciklamasi\")\n\nrouter_prompt = ChatPromptTemplate.from_messages([\n    (\"system\", \"\"\"Sen bir musteri mesaji siniflandiricisin.\nDepartmanlar:\n- faq: Genel sorular, urun bilgisi, nasil yapilir\n- billing: Fatura, odeme, abonelik, iade\n- tech_support: Teknik sorun, hata, bug\n\nOrnekler:\n\\\"Aylik planin fiyati nedir?\\\" -> faq\n\\\"Faturamda fazla ucret var\\\" -> billing\n\\\"Sayfa yuklenmiyor\\\" -> tech_support\n\nSADECE JSON olarak yanit ver.\"\"\"),\n    (\"human\", \"{message}\")\n])\n\nparser = JsonOutputParser(pydantic_object=RouterDecision)\n\nasync def router_node(state: AgentState) -> dict:\n    llm = ChatOpenAI(model=settings.openai_model, temperature=0, api_key=settings.openai_api_key)\n    chain = router_prompt | llm | parser\n    last_message = state[\"messages\"][-1].content\n    \n    try:\n        decision = await chain.ainvoke({\"message\": last_message})\n        intent = decision[\"intent\"]\n        confidence = decision.get(\"confidence\", 0.8)\n    except Exception:\n        intent = \"faq\"\n        confidence = 0.3\n    \n    if confidence < settings.confidence_threshold:\n        intent = \"fallback\"\n    \n    return {\n        \"current_agent\": intent,\n        \"customer_intent\": intent,\n        \"confidence_score\": confidence,\n        \"routing_history\": state.get(\"routing_history\", []) + [intent],\n        \"turn_count\": state.get(\"turn_count\", 0) + 1\n    }",
      "deep_dive": "Router'da temperature=0 kullan\u0131yoruz \u00e7\u00fcnk\u00fc routing deterministic olmal\u0131. JsonOutputParser, LLM'in JSON \u00e7\u0131kt\u0131s\u0131n\u0131 otomatik parse eder. Few-shot \u00f6rnekleri system prompt'a eklemek, LLM'in s\u0131n\u0131fland\u0131rma accuracy'sini dramatik art\u0131r\u0131r \u2014 bu in-context learning'dir.",
      "checkpoint": "10 farkl\u0131 T\u00fcrk\u00e7e m\u00fc\u015fteri mesaj\u0131yla test et. En az %90 do\u011fru routing olmal\u0131."
    },
    {
      "title": "Billing ve Tech Support Agent'lar\u0131n\u0131 Olu\u015ftur",
      "why": "Her specialist agent kendi system prompt'u ve ba\u011flam\u0131 ile \u00e7al\u0131\u015fmal\u0131. Billing agent para/fatura konusunda uzman, tech support agent teknik sorunlarda uzman olmal\u0131.",
      "instructions": "Billing ve Tech Support agent'lar\u0131n\u0131 olu\u015ftur. Her birine domain-specific system prompt yaz. Agent'lar\u0131 graph'a entegre et.",
      "code_snippet": "# agents/billing_agent.py\nfrom langchain_openai import ChatOpenAI\nfrom langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder\nfrom graph.state import AgentState\nfrom config.settings import get_settings\n\nsettings = get_settings()\nllm = ChatOpenAI(model=settings.openai_model, temperature=0.3, api_key=settings.openai_api_key)\n\nbilling_prompt = ChatPromptTemplate.from_messages([\n    (\"system\", \"\"\"Sen TechCorp'un fatura ve odeme uzmanisin.\nBilgiler:\n- Free Plan: Ucretsiz, 3 proje limiti\n- Pro Plan: 99 TL/ay, sinirsiz proje\n- Enterprise: Ozel fiyat, SLA garantisi\n- Iade politikasi: 14 gun icinde tam iade\n\nKurallar:\n- Turkce yanit ver\n- Hassas bilgileri asla isteme\n- Fatura detayi icin musteri ID'si iste\"\"\"),\n    MessagesPlaceholder(variable_name=\"messages\"),\n])\n\nasync def billing_node(state: AgentState) -> dict:\n    chain = billing_prompt | llm\n    response = await chain.ainvoke({\"messages\": state[\"messages\"]})\n    return {\"messages\": [response], \"current_agent\": \"billing\"}\n\n\n# agents/tech_support_agent.py\ntech_prompt = ChatPromptTemplate.from_messages([\n    (\"system\", \"\"\"Sen TechCorp'un teknik destek uzmanisin.\nYaygin sorunlar:\n1. Sayfa yuklenmiyor -> Cache temizle, farkli tarayici dene\n2. Giris yapilamiyor -> Sifre sifirlama, cookie kontrol\n3. Dosya yuklenmiyor -> Max 50MB, PDF/DOCX/PNG/JPG\n4. Yavas performans -> Uzantilari devre disi birak\n5. API hatasi -> API key kontrolu, rate limit\n\nKurallar:\n- Adim adim troubleshooting yap\n- 3 adimda cozulemezse insan agent'a yonlendir\"\"\"),\n    MessagesPlaceholder(variable_name=\"messages\"),\n])\n\nasync def tech_support_node(state: AgentState) -> dict:\n    chain = tech_prompt | llm\n    response = await chain.ainvoke({\"messages\": state[\"messages\"]})\n    return {\"messages\": [response], \"current_agent\": \"tech_support\"}",
      "deep_dive": "Her agent'\u0131n system prompt'u, o agent'\u0131n 'beyni'dir \u2014 ne bildi\u011fini, nas\u0131l davranmas\u0131 gerekti\u011fini ve s\u0131n\u0131rlar\u0131n\u0131 tan\u0131mlar. Her agent i\u00e7in ayr\u0131 LLM instance yerine ayn\u0131 model'i farkl\u0131 prompt'larla kullan\u0131yoruz \u2014 connection pooling ve kaynak optimizasyonu sa\u011flar.",
      "checkpoint": "Her 3 agent T\u00fcrk\u00e7e ve domain-specific yan\u0131tlar vermeli. Router ile end-to-end test: mesaj -> routing -> agent yan\u0131t\u0131 ak\u0131\u015f\u0131 \u00e7al\u0131\u015fmal\u0131."
    },
    {
      "title": "FastAPI Endpoint'leri ile Chat API",
      "why": "Agent'lar\u0131 HTTP API olarak expose etmeden frontend veya di\u011fer servisler kullanamaz. FastAPI async deste\u011fi ile LLM \u00e7a\u011fr\u0131lar\u0131n\u0131 bloklamadan handle eder.",
      "instructions": "FastAPI uygulamas\u0131 olu\u015ftur. POST /chat endpoint'i: mesaj al, session_id ile memory'den ge\u00e7mi\u015fi y\u00fckle, graph'\u0131 \u00e7al\u0131\u015ft\u0131r, yan\u0131t\u0131 d\u00f6nd\u00fcr. Health check endpoint. CORS middleware ekle.",
      "code_snippet": "# api/routes.py\nfrom fastapi import FastAPI, HTTPException\nfrom fastapi.middleware.cors import CORSMiddleware\nfrom pydantic import BaseModel\nfrom uuid import uuid4\nfrom langchain_core.messages import HumanMessage\nfrom graph.workflow import build_graph\nfrom graph.state import create_initial_state\nfrom services.memory_service import memory_service\nfrom config.settings import get_settings\n\nsettings = get_settings()\napp = FastAPI(title=\"AI Customer Support API\", version=\"1.0.0\")\napp.add_middleware(CORSMiddleware, allow_origins=settings.cors_origins, allow_methods=[\"*\"], allow_headers=[\"*\"])\n\ngraph = build_graph()\n\nclass ChatRequest(BaseModel):\n    message: str\n    session_id: str | None = None\n\nclass ChatResponse(BaseModel):\n    response: str\n    session_id: str\n    agent: str\n    sentiment_score: float\n    needs_human: bool\n\n@app.post(\"/chat\", response_model=ChatResponse)\nasync def chat(request: ChatRequest):\n    session_id = request.session_id or str(uuid4())\n    previous_messages = await memory_service.get_messages(session_id)\n    human_msg = HumanMessage(content=request.message)\n    all_messages = list(previous_messages) + [human_msg]\n    \n    state = create_initial_state(session_id)\n    state[\"messages\"] = all_messages\n    \n    prev_meta = await memory_service.get_session_metadata(session_id)\n    if prev_meta:\n        state[\"turn_count\"] = prev_meta.get(\"turn_count\", 0)\n        state[\"sentiment_score\"] = prev_meta.get(\"sentiment_score\", 0.5)\n    \n    try:\n        result = await graph.ainvoke(state)\n    except Exception as e:\n        raise HTTPException(status_code=500, detail=f\"Agent error: {str(e)}\")\n    \n    ai_response = result[\"messages\"][-1].content\n    await memory_service.add_message(session_id, human_msg)\n    await memory_service.add_message(session_id, result[\"messages\"][-1])\n    await memory_service.save_session_metadata(session_id, {\n        \"turn_count\": result.get(\"turn_count\", 0),\n        \"sentiment_score\": result.get(\"sentiment_score\", 0.5),\n        \"routing_history\": result.get(\"routing_history\", []),\n    })\n    \n    return ChatResponse(\n        response=ai_response, session_id=session_id,\n        agent=result.get(\"current_agent\", \"unknown\"),\n        sentiment_score=result.get(\"sentiment_score\", 0.5),\n        needs_human=result.get(\"needs_human\", False)\n    )\n\n@app.get(\"/health\")\nasync def health_check():\n    return {\"status\": \"healthy\", \"version\": \"1.0.0\"}",
      "deep_dive": "FastAPI'nin async deste\u011fi kritiktir \u2014 LLM API \u00e7a\u011fr\u0131lar\u0131 genellikle 1-3 saniye s\u00fcrer ve senkron framework'lerde thread bloklan\u0131r. Async ile ayn\u0131 anda onlarca konu\u015fmay\u0131 handle edebilirsin. Graph'\u0131 mod\u00fcl seviyesinde compile ediyoruz \u2014 her request'te yeniden compile etmek gereksiz overhead'dir.",
      "checkpoint": "uvicorn main:app \u00e7al\u0131\u015ft\u0131r. curl ile POST /chat'e mesaj g\u00f6nder. Yan\u0131t ChatResponse format\u0131nda d\u00f6nmeli. Ayn\u0131 session_id ile ikinci mesaj g\u00f6nderdi\u011finde \u00f6nceki konu\u015fmay\u0131 hat\u0131rlamal\u0131."
    }
  ]
}

data["milestones"].append(m2)

with open(OUT, "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)
print("M2 done, size:", os.path.getsize(OUT))
