import json

def t(term, translation, pronunciation, difficulty, domain, def_en, def_tr, ex_en, ex_tr, ex_ctx, patterns, scenario, mistakes, related):
    return {
        "term": term,
        "translation": translation,
        "pronunciation": pronunciation,
        "difficulty_level": difficulty,
        "domain": domain,
        "definition_en": def_en,
        "definition_tr": def_tr,
        "example_sentences": [{"en": ex_en, "tr": ex_tr, "context": ex_ctx}],
        "common_patterns": patterns if isinstance(patterns, list) else [patterns],
        "scenario": scenario,
        "common_mistakes": mistakes,
        "related_terms": related,
        "lesson_id": ""
    }

terms = []

# PROGRAMMING DOMAIN (~70 terms)
terms.append(t("variable","Degisken","VER-i-ibil","beginner","programming","A named storage location in memory that holds a value","Bellekte deger tutan isimlendirilmis depolama alani","Declare a variable to store the user's name.","Kullanicinin adini saklamak icin bir degisken tanimla.","Junior developer'a kod yazarken anlatirsin",["declare a variable — degisken tanimlamak","assign a value to a variable — degiskene deger atamak"],"Pair programming sirasinda: 'Let's create a variable to keep track of the count.'","Turk gelistiriciler 'variable' yerine 'degisken' deyip Ingilizce konusmada karistirabilir.",["constant","scope","type"]))
terms.append(t("function","Fonksiyon","FANK-sin","beginner","programming","A reusable block of code that performs a specific task","Belirli bir gorevi yerine getiren yeniden kullanilabilir kod blogu","This function calculates the total price.","Bu fonksiyon toplam fiyati hesaplar.","Code review'da kodunu acklarken",["call a function — fonksiyon cagirmak","define a function — fonksiyon tanimlamak"],"Takim arkadasin soruyor: 'Can you extract this logic into a separate function?'","'Function' kelimesini 'method' ile karistirmak yaygindir.",["method","parameter","return"]))
terms.append(t("parameter","Parametre","pi-RA-mi-tir","beginner","programming","A variable in a function definition that receives a value when called","Fonksiyon taniminda listelenen ve cagrildiginda deger alan degisken","This function takes two parameters: name and age.","Bu fonksiyon iki parametre alir: isim ve yas.","API dokumantasyonu yazarken",["pass a parameter — parametre gecmek","optional parameter — opsiyonel parametre"],"Code review'da: 'You should add a timeout parameter to this function.'","'Parameter' ve 'argument' farkini bilmemek yaygin hatadir.",["argument","function","default value"]))
terms.append(t("return","Geri dondurmek","ri-TORN","beginner","programming","A statement that exits a function and optionally sends back a value","Fonksiyondan cikisi saglayan ve istege bagli deger gonderen ifade","The function should return an array of results.","Fonksiyon bir sonuc dizisi dondurmeli.","Teknik tasarim tartismasinda",["return a value — deger dondurmek","return early — erken donmek"],"Pair programming: 'Why doesn't this function return anything?'","'Return etmek' kullanimi yaygindir, Turkce'ye cevirmeye gerek yok.",["function","output","void"]))
terms.append(t("loop","Dongu","LUUP","beginner","programming","A control structure that repeats code until a condition is met","Bir kosul saglanana kadar kodu tekrarlayan kontrol yapisi","Use a loop to iterate over the array.","Dizi uzerinde gezinmek icin dongu kullan.","Junior developer'a algoritma anlatirken",["loop through — uzerinde dongu yapmak","break out of a loop — dongudan cikmak"],"Code review: 'This nested loop is O(n^2). Can we optimize it?'","'Loop' ve 'iterate' arasindaki farki bilmemek.",["for","while","iteration","break"]))
terms.append(t("array","Dizi","i-REY","beginner","programming","An ordered collection of elements accessible by index","Indeks ile erisilebilen sirali eleman koleksiyonu","Store the results in an array.","Sonuclari bir dizide sakla.","Veri isleme kodu yazarken",["array of X — X dizisi","push to an array — diziye eklemek"],"Standup: 'I'm converting the response into an array of objects.'","'Array' ile 'list' teknik farkini bilmemek.",["list","index","element","collection"]))
terms.append(t("object","Nesne","OB-cikt","beginner","programming","A data structure that stores key-value pairs","Anahtar-deger ciftlerini saklayan veri yapisi","Create an object to represent the user.","Kullaniciyi temsil etmek icin bir nesne olustur.","Model tasarimi yaparken",["create an object — nesne olusturmak","object property — nesne ozelligi"],"Teknik tartisma: 'Pass the configuration as an object.'","'Object' kelimesini 'obje' ile karistirmak.",["class","property","method","instance"]))
terms.append(t("class","Sinif","KLAS","beginner","programming","A blueprint for creating objects with properties and methods","Ozellik ve metotlarla nesne olusturmak icin sablon","Define a class for the payment service.","Odeme servisi icin bir sinif tanimla.","Backend servis mimarisi tasarlarken",["extend a class — sinifi genisletmek","instantiate a class — siniftan ornek olusturmak"],"Architecture: 'Should we create a base class that all services inherit from?'","'Class' ile 'type' farkini bilmemek.",["object","inheritance","instance","constructor"]))
terms.append(t("inheritance","Kalitim","in-HER-i-tins","intermediate","programming","A mechanism where a class acquires properties from a parent class","Bir sinifin ust siniftan ozellik ve metotlari devralma mekanizmasi","Use inheritance to share common behavior between classes.","Siniflar arasinda ortak davranisi paylasmak icin kalitim kullan.","OOP tasarim tartismasinda",["inherit from — den kalitim almak","single inheritance — tekli kalitim"],"Code review: 'Consider using inheritance from the base class.'","'Inheritance' yerine 'miras' demek teknik ortamda uygun degil.",["class","polymorphism","extends","super"]))
terms.append(t("polymorphism","Cok bicimlilik","po-li-MOR-fi-zim","intermediate","programming","The ability of different classes to respond differently to the same method call","Farkli siniflarin ayni metot cagrisina farkli yanit verebilmesi","Polymorphism allows us to treat different shapes uniformly.","Cok bicimlilik farkli sekilleri tek tip ele almamizi saglar.","OOP prensiplerini anlatirken",["runtime polymorphism — calisma zamani cok bicimliligi","method overriding — metot ezme"],"Mulakat: 'Can you explain polymorphism with a real-world example?'","Polimorfizmi sadece method overriding olarak bilmek.",["inheritance","interface","override","overload"]))
terms.append(t("encapsulation","Kapsulleme","en-kap-su-LEY-sin","intermediate","programming","Bundling data and methods while restricting direct access to internals","Veri ve metotlari bir arada tutarken ic duruma erisimi kisitlama","Encapsulation helps us hide implementation details.","Kapsulleme uygulama detaylarini gizlememize yardimci olur.","Clean code tartismasinda",["encapsulate the logic — mantigi kapsullemek"],"Code review: 'This class exposes too many internals.'","Encapsulation'i sadece private/public olarak dusunmek.",["private","public","getter","setter"]))
terms.append(t("abstraction","Soyutlama","ab-STRAK-sin","intermediate","programming","Hiding complex details and showing only essential features","Karmasik detaylari gizleyip sadece temel ozellikleri gosterme","The database layer provides an abstraction over raw SQL.","Veritabani katmani ham SQL uzerinde bir soyutlama saglar.","Mimari tasarim toplantisinda",["abstract away — soyutlamak","leaky abstraction — sizdiran soyutlama"],"Teknik tartisma: 'We need a better abstraction here.'","'Abstraction' ile 'abstract class' karistirmak.",["interface","encapsulation","abstract class"]))
terms.append(t("interface","Arayuz","IN-tir-feys","intermediate","programming","A contract defining what methods a class must implement","Bir sinifin hangi metotlari uygulamasi gerektigini tanimlayan sozlesme","Define an interface for the payment gateway.","Odeme gecidi icin bir arayuz tanimla.","Servis entegrasyonu tasarlarken",["implement an interface — arayuz uygulamak","expose an interface — arayuz sunmak"],"Architecture: 'Define a common interface so we can swap providers.'","UI interface ile programming interface karistirmak.",["abstract class","contract","implementation"]))
terms.append(t("enum","Numaralandirma","I-nam","intermediate","programming","A data type consisting of a set of named constants","Isimlendirilmis sabitlerden olusan veri tipi","Use an enum to define order status values.","Siparis durumu degerlerini tanimlamak icin enum kullan.","Backend model tasariminda",["define an enum — enum tanimlamak","enum member — enum uyesi"],"Code review: 'Use an enum instead of magic strings.'","'Enum' telaffuzunu yanlis yapmak.",["constant","type","union type"]))
terms.append(t("generic","Jenerik","ci-NE-rik","advanced","programming","A feature allowing code that works with multiple types safely","Tip guvenligiyle birden fazla tipte calisan kod yazma ozelligi","Create a generic function that works with any data type.","Herhangi bir veri tipiyle calisan jenerik fonksiyon olustur.","TypeScript utility function yazarken",["generic type — jenerik tip","generic constraint — jenerik kisitlama"],"Code review: 'Make this function generic for both User and Admin.'","Generic'leri sadece TypeScript'e ozgu sanmak.",["type parameter","constraint","type safety"]))
terms.append(t("type","Tip","TAYP","beginner","programming","A classification specifying what kind of value a variable can hold","Bir degiskenin hangi tur deger tutabilecegini belirleyen siniflandirma","What type does this function return?","Bu fonksiyon hangi tipi donduruyor?","Kod incelemesi sirasinda",["type checking — tip kontrolu","type inference — tip cikarimi"],"Standup: 'I spent the morning fixing type errors.'","'Type' ve 'class' farkini bilmemek.",["string","integer","boolean","interface"]))
terms.append(t("string","Karakter dizisi","STRING","beginner","programming","A sequence of characters used to represent text","Metni temsil etmek icin kullanilan karakter dizisi","Convert the number to a string before displaying it.","Sayiyi gostermeden once string'e cevir.","Frontend'de veri gosteriminde",["string concatenation — string birlestirme","parse a string — string'i ayristirmak"],"Debug: 'The API is returning a string instead of a number.'","String interpolation ve concatenation farkini bilmemek.",["character","substring","template literal"]))
terms.append(t("integer","Tam sayi","IN-ti-cir","beginner","programming","A whole number without a decimal point","Ondalik noktasi olmayan tam sayi","The ID field should be an integer.","ID alani bir tam sayi olmali.","Veritabani semasi tasarlarken",["integer overflow — tam sayi tasmasi","cast to integer — tam sayiya donusturmek"],"Bug: 'The price field is stored as integer, but we need decimal.'","JavaScript'te integer ve float ayriminin olmadigini bilmemek.",["float","number","BigInt"]))
terms.append(t("float","Ondalikli sayi","FLOUT","beginner","programming","A number with a decimal point for fractional values","Kesirli degerleri temsil eden ondalikli sayi","Use a float for the price calculation.","Fiyat hesaplamasi icin float kullan.","E-ticaret backend gelistirirken",["floating point precision — kayan nokta hassasiyeti"],"Bug: '0.1 + 0.2 is not exactly 0.3.'","Para hesaplamalarinda float kullanmak.",["integer","decimal","precision"]))
terms.append(t("boolean","Mantiksal deger","BUU-li-in","beginner","programming","A data type that can only be true or false","Yalnizca true veya false olabilen veri tipi","The isActive field is a boolean.","isActive alani bir boolean'dir.","Kullanici modeli tasarlarken",["boolean flag — boolean bayrak","toggle a boolean — boolean degerini degistirmek"],"Code review: 'Use a boolean for the enabled flag.'","Boolean isimlendirmede 'is', 'has', 'can' prefix kullanmamak.",["true","false","truthy","falsy"]))
terms.append(t("null","Bos deger","NAL","beginner","programming","A special value representing the intentional absence of any value","Herhangi bir degerin bilincli yoklugunu temsil eden ozel deger","Check if the value is null before accessing properties.","Ozelliklerine erismeden once null kontrolu yap.","Defensive programming yaparken",["null check — null kontrolu","nullable — null olabilir"],"Bug fix: 'The app crashes because we're not handling null.'","Null ile undefined farkini bilmemek.",["undefined","nil","optional"]))
terms.append(t("undefined","Tanimsiz","an-di-FAYND","beginner","programming","A value assigned to variables declared but not initialized","Tanimlanmis ama deger atanmamis degiskenlere verilen deger","The variable is undefined because it was never assigned.","Degisken hic atanmadigi icin undefined.","Debug sirasinda",["check for undefined — undefined kontrolu"],"Debug: 'Why is this undefined? We forgot to initialize state.'","typeof null === 'object' oldugunu bilmemek.",["null","void","uninitialized"]))
terms.append(t("scope","Kapsam","SKOUP","intermediate","programming","The region of code where a variable is accessible","Bir degiskenin erisilebilir oldugu kod bolgesi","This variable is out of scope here.","Bu degisken burada kapsam disinda.","Hata ayiklarken",["global scope — global kapsam","block scope — blok kapsami"],"Code review: 'Move this variable to a narrower scope.'","var, let, const scope farklarini bilmemek.",["closure","hoisting","global","local"]))
terms.append(t("closure","Kapanis","KLO-jir","advanced","programming","A function retaining access to its outer scope variables","Dis kapsamdaki degiskenlere erisimi koruyan fonksiyon","This callback creates a closure over the counter variable.","Bu callback counter uzerinde closure olusturuyor.","Ileri seviye JavaScript tartismasinda",["closure over X — X uzerinde closure"],"Mulakat: 'Can you explain closures with a practical example?'","Closure'i sadece teorik bilmek.",["scope","lexical environment","callback"]))
terms.append(t("hoisting","Yukari tasima","HOYST-ing","intermediate","programming","JavaScript behavior of moving declarations to the top of scope","JavaScript'in tanimlamalari kapsaminin en ustune tasima davranisi","Variable hoisting can cause unexpected behavior.","Degisken hoisting beklenmeyen davranislara yol acabilir.","JavaScript egitiminde",["hoisted to the top — en uste tasinmis"],"Bug: 'The issue is caused by hoisting.'","let ve const'un hoisting yapilmadigini sanmak.",["scope","var","let","temporal dead zone"]))
terms.append(t("callback","Geri cagirma fonksiyonu","KOL-bek","intermediate","programming","A function passed as an argument to be executed later","Daha sonra calistirilmak uzere arguman olarak gecilen fonksiyon","Pass a callback function to handle the response.","Yaniti islemek icin callback fonksiyonu gec.","Asenkron programlamada",["callback function — geri cagirma fonksiyonu","callback hell — callback cehennemi"],"Code review: 'This nested callback is hard to read.'","Callback hell'e dusmek.",["promise","async","event handler"]))
terms.append(t("promise","Soz / Promise","PRO-mis","intermediate","programming","An object representing eventual completion of an async operation","Asenkron islemin nihai tamamlanmasini temsil eden nesne","This API call returns a promise.","Bu API cagrisi bir promise dondurur.","Frontend gelistirmede",["resolve a promise — promise cozmek","chain promises — promise zincirleme"],"Debug: 'You're not awaiting the promise.'","Promise'i await etmeyi unutmak.",["async","await","then","catch"]))
terms.append(t("async","Asenkron","EY-sink","intermediate","programming","A keyword declaring a function as asynchronous","Bir fonksiyonu asenkron tanimlayan anahtar kelime","Mark the function as async to use await.","Await kullanmak icin fonksiyonu async isaretle.","API cagrisi yazarken",["async function — asenkron fonksiyon","async operation — asenkron islem"],"Code review: 'This function makes API calls but isn't async.'","Her fonksiyonu gereksiz yere async yapmak.",["await","promise","synchronous"]))
terms.append(t("await","Beklemek","i-WEYT","intermediate","programming","A keyword pausing async execution until a promise settles","Promise cozulene kadar yurutmeyi durduran anahtar kelime","Await the database query before processing results.","Sonuclari islemeden once veritabani sorgusunu await et.","Backend serviste",["await the result — sonucu beklemek"],"Bug: 'You forgot to await this call.'","await'i try-catch ile sarmamak.",["async","promise","then"]))
terms.append(t("iterator","Yineleyici","I-ti-rey-tir","advanced","programming","An object providing a mechanism to traverse a collection","Koleksiyonu eleman eleman gezme mekanizmasi saglayan nesne","Implement the iterator protocol for this collection.","Bu koleksiyon icin iterator protokolunu uygula.","Ozel veri yapisi olustururken",["iterate over — uzerinde yinelemek"],"Code review: 'Implement iterator protocol for for...of loops.'","Iterator ve iterable farkini bilmemek.",["generator","iterable","for...of"]))
terms.append(t("generator","Uretici","CE-ni-rey-tir","advanced","programming","A function that can be paused and resumed, yielding values","Duraklatilip devam ettirilebilen ve deger ureten fonksiyon","Use a generator to lazily produce values.","Tembel deger uretimi icin generator kullan.","Performans optimizasyonunda",["yield a value — deger vermek","generator function — generator fonksiyonu"],"Teknik: 'A generator is perfect for lazy evaluation.'","Generator'lari sadece Redux-Saga'da kullanmak.",["iterator","yield","lazy evaluation"]))
terms.append(t("decorator","Dekorator","DE-ko-rey-tir","advanced","programming","A pattern adding behavior without modifying structure","Yapiyi degistirmeden davranis ekleyen tasarim kalibi","Apply a logging decorator to track function calls.","Fonksiyon cagrilarini izlemek icin logging dekoratoru uygula.","Cross-cutting concerns eklerken",["@decorator — dekorator uygulama","decorator pattern — dekorator kalibi"],"Code review: 'Use a decorator for authentication checks.'","Decorator'lari asiri kullanmak.",["annotation","middleware","higher-order function"]))
terms.append(t("module","Modul","MO-dyul","beginner","programming","A self-contained unit of code that can be imported","Bagimsiz kod birimi","Import the authentication module.","Kimlik dogrulama modulunu ice aktar.","Proje yapisini organize ederken",["import a module — modul ice aktarmak"],"Architecture: 'Split this into separate modules.'","CommonJS ve ES Modules farkini bilmemek.",["import","export","package"]))
terms.append(t("import","Ice aktarmak","IM-port","beginner","programming","A statement bringing code from another module","Baska modulden kodu getiren ifade","Import the utility functions from helpers.","Yardimci fonksiyonlari ice aktar.","Kod yazarken",["import from — den ice aktarmak","named import — isimli ice aktarma"],"Code review: 'Use named imports.'","Circular import sorunlarindan habersiz olmak.",["export","module","require"]))
terms.append(t("export","Disa aktarmak","EKS-port","beginner","programming","A statement making code available for import","Kodu diger modullerin kullanabilecegi hale getiren ifade","Export the component so other files can use it.","Bileseni disa aktar.","React component gelistirirken",["export default — varsayilan disa aktarma","named export — isimli disa aktarma"],"Code review: 'This utility should be exported.'","Her seyi export default yapmak.",["import","module","public API"]))
terms.append(t("package","Paket","PA-kic","beginner","programming","A collection of related modules distributed as one unit","Tek birim olarak dagitilan modul koleksiyonu","Install the lodash package from npm.","npm'den lodash paketini kur.","Bagimliliklari yonetirken",["install a package — paket kurmak","publish a package — paket yayinlamak"],"Standup: 'I need a package for date formatting.'","Her kucuk is icin paket kurmak.",["module","dependency","npm","yarn"]))
terms.append(t("dependency","Bagimlilik","di-PEN-din-si","intermediate","programming","An external package a project requires to function","Projenin calismasi icin gereken harici paket","Update dependencies to fix the security vulnerability.","Guvenlik acigini duzeltmek icin bagimliliklari guncelle.","Security audit sonrasinda",["install dependencies — bagimliliklari kurmak","dependency tree — bagimlilik agaci"],"Sprint: 'Critical security update in a dependency.'","devDependencies ve dependencies farkini bilmemek.",["package","version","node_modules"]))
terms.append(t("runtime","Calisma zamani","RAN-taym","intermediate","programming","The period during which a program executes","Programin calistigi sure veya ortam","This error only occurs at runtime.","Bu hata yalnizca calisma zamaninda olusur.","Hata ayiklarken",["runtime error — calisma zamani hatasi","runtime environment — calisma zamani ortami"],"Bug: 'This passes type checking but fails at runtime.'","Compile time ve runtime hatalarini karistirmak.",["compile time","execution","Node.js"]))
terms.append(t("compile","Derlemek","kim-PAYL","intermediate","programming","To transform source code into another language","Kaynak kodu baska bir dile donusturmek","Compile TypeScript files before deploying.","Deploy etmeden once TypeScript dosyalarini derle.","Build pipeline'inda",["compile the code — kodu derlemek","compilation error — derleme hatasi"],"CI/CD: 'Build failed because code doesn't compile.'","Compile ve transpile farkini bilmemek.",["transpile","build","runtime"]))
terms.append(t("transpile","Donusturmek","trans-PAYL","intermediate","programming","To convert code from one high-level language to another","Kaynak kodu bir ust duzey dilden digerine donusturmek","Babel transpiles modern JavaScript to ES5.","Babel modern JavaScript'i ES5'e donusturur.","Build yapilandirmasinda",["transpile to — ye donusturmek"],"Setup: 'Configure transpiler to target older browsers.'","Transpile'i compile ile ayni sanmak.",["compile","Babel","TypeScript"]))
terms.append(t("parse","Ayristirmak","PARS","intermediate","programming","To analyze a string and convert it into a usable format","String'i analiz edip kullanilabilir formata donusturmek","Parse the JSON response from the API.","API'den gelen JSON yanitini ayristir.","API entegrasyonunda",["parse JSON — JSON ayristirmak","parse error — ayristirma hatasi"],"Debug: 'We need to parse the response string into JSON.'","JSON.parse() icin try-catch kullanmamak.",["serialize","JSON","stringify"]))
terms.append(t("serialize","Serilestirmek","SIR-i-layz","intermediate","programming","To convert a data structure into a storable or transmittable format","Veri yapisini saklanabilir formata donusturmek","Serialize the object to JSON before sending.","Gondermeden once nesneyi JSON'a serilestir.","API yaniti olustururken",["serialize to JSON — JSON'a serilestirmek"],"Architecture: 'Which serialization format? JSON or Protocol Buffers?'","Circular reference nesneleri serilestirmeye calismak.",["deserialize","JSON","marshal"]))
terms.append(t("deserialize","Seriden cikarmak","di-SIR-i-layz","intermediate","programming","To convert serialized data back into a usable structure","Serilestilmis veriyi kullanilabilir yapiya donusturmek","Deserialize the request body into a User object.","Istek govdesini User nesnesine donustur.","Backend controller'da",["deserialize from JSON — JSON'dan donusturmek"],"Bug: 'Deserialization fails because of unexpected date format.'","Deserialize ederken veri dogrulama yapmamak.",["serialize","parse","unmarshal"]))
terms.append(t("debug","Hata ayiklamak","di-BAG","beginner","programming","The process of finding and fixing errors in code","Koddaki hatalari bulma ve duzeltme sureci","I spent the morning debugging this issue.","Sabahi bu sorunu debug ederek gecirdim.","Standup'ta guncelleme verirken",["debug the issue — sorunu debug etmek","debugging session — debug oturumu"],"Standup: 'Still debugging the payment issue.'","Console.log ile debug etmeye alisip debugger kullanmamak.",["breakpoint","stack trace","log"]))
terms.append(t("breakpoint","Kesme noktasi","BREYK-poynt","intermediate","programming","A point where execution pauses for inspection","Yurutmenin duraklayacagi kod noktasi","Set a breakpoint on line 42.","42. satira breakpoint koy.","IDE'de debug yaparken",["set a breakpoint — breakpoint koymak","hit a breakpoint — breakpoint'e ulasmak"],"Pair debugging: 'Set a breakpoint here and step through.'","Her yere console.log yazmak.",["debug","step over","step into","watch"]))
terms.append(t("stack trace","Yigin izi","STAK treys","intermediate","programming","A report of active stack frames during execution","Calisma sirasindaki aktif yigin cercevelerinin raporu","Check the stack trace to find the error origin.","Hatanin kaynagini bulmak icin stack trace kontrol et.","Production hatasi incelerken",["read the stack trace — stack trace okumak"],"Bug report: 'Paste the stack trace.'","Stack trace okumayi bilmemek.",["error","exception","call stack"]))
terms.append(t("exception","Istisna","ik-SEP-sin","intermediate","programming","An event disrupting normal program flow","Programin normal akisini bozan olay","The function throws an exception for invalid input.","Gecersiz girdide fonksiyon istisna firlatir.","Error handling yazarken",["throw an exception — istisna firlatmak","catch an exception — istisna yakalamak"],"Code review: 'Catch this exception.'","Genel Exception yakalamak.",["error","try-catch","throw"]))
terms.append(t("error handling","Hata yonetimi","ER-ir HEND-ling","intermediate","programming","Anticipating and managing errors during execution","Hatalari ongorme ve yonetme pratigi","We need better error handling in the API layer.","API katmaninda daha iyi hata yonetimine ihtiyacimiz var.","Kod kalitesini artirirken",["implement error handling — hata yonetimi uygulamak"],"Retro: 'Our error handling is inconsistent.'","Hatalari sessizce yutmak (empty catch block).",["try-catch","exception","error boundary"]))
terms.append(t("try-catch","Dene-Yakala","TRAY kec","beginner","programming","A control structure for catching exceptions","Istisnalari yakalama kontrol yapisi","Wrap the API call in a try-catch block.","API cagrisini try-catch bloguyla sar.","Hata yonetimi eklerken",["try-catch block — try-catch blogu","try-catch-finally — dene-yakala-sonunda"],"Code review: 'This async call needs a try-catch.'","Try-catch'i cok genis tutmak.",["exception","throw","finally"]))
terms.append(t("throw","Firlatmak","TROU","intermediate","programming","A statement generating an exception to signal an error","Hata bildirmek icin istisna ureten ifade","Throw an error if the user is not authenticated.","Kullanici dogrulanmamissa hata firlat.","Middleware yazarken",["throw new Error — yeni hata firlatmak"],"Code review: 'Throw an error instead of returning null.'","String firlatmak. Error nesnesi firlatmak gerekir.",["catch","exception","error"]))
terms.append(t("recursion","Ozyineleme","ri-KOR-jin","intermediate","programming","A technique where a function calls itself","Fonksiyonun kendini cagirma teknigi","Use recursion to traverse the tree.","Agaci gezmek icin ozyineleme kullan.","Veri yapisi algoritmalarinda",["recursive function — ozyinelemeli fonksiyon","base case — temel durum"],"Mulakat: 'Solve this with recursion. What's the base case?'","Base case tanimlamamak.",["base case","stack overflow","tail recursion"]))
terms.append(t("algorithm","Algoritma","AL-go-ri-dim","beginner","programming","A step-by-step procedure for solving a problem","Bir problemi cozmek icin adim adim prosedur","We need a more efficient algorithm.","Daha verimli bir algoritmaya ihtiyacimiz var.","Performans optimizasyonunda",["sorting algorithm — siralama algoritmasi","search algorithm — arama algoritmasi"],"Mulakat: 'Walk me through your algorithm.'","Karmasikligi dusunmeden brute force cozmek.",["data structure","time complexity","Big O"]))
terms.append(t("data structure","Veri yapisi","DEY-ti STRAK-cir","beginner","programming","A way of organizing data for efficient access","Verileri verimli erisim icin organize etme yontemi","Choose the right data structure for your use case.","Dogru veri yapisini secin.","Sistem tasariminda",["data structure and algorithm — veri yapisi ve algoritma"],"Mulakat: 'What data structure for an LRU cache?'","Her sey icin array kullanmak.",["array","hash map","tree","graph"]))
terms.append(t("hash map","Hash haritasi","HAS mep","intermediate","programming","A data structure with O(1) average key-value lookup","O(1) ortalama anahtar-deger aramasi yapan veri yapisi","Use a hash map for constant-time lookups.","Sabit zamanli aramalar icin hash map kullan.","Performans optimizasyonunda",["hash map lookup — hash map aramasi","hash collision — hash cakismasi"],"Mulakat: 'A hash map gives O(1) lookup.'","Object ve Map farkini bilmemek.",["dictionary","object","key-value"]))
terms.append(t("linked list","Bagli liste","LINKD list","intermediate","programming","A linear data structure with pointer-connected elements","Isaretcilerle baglanan elemanlardan olusan dogrusal veri yapisi","Implement a singly linked list.","Tek yonlu bagli liste uygula.","Veri yapilari odevinde",["singly linked list — tek yonlu bagli liste","doubly linked list — cift yonlu bagli liste"],"Mulakat: 'How to detect a cycle in a linked list?'","Her zaman yavas oldugunu sanmak.",["node","pointer","array"]))
terms.append(t("tree","Agac","TRII","intermediate","programming","A hierarchical data structure of nodes and edges","Dugum ve kenarlardan olusan hiyerarsik veri yapisi","The DOM is structured as a tree.","DOM bir agac yapisi olarak duzenlenmistir.","Frontend gelistirmede",["binary tree — ikili agac","tree traversal — agac gezinmesi"],"Mulakat: 'Find the depth of a binary tree.'","Traversal yontemlerini karistirmak.",["node","binary search tree","root","leaf"]))
terms.append(t("graph","Graf","GRAF","advanced","programming","A data structure with nodes and edges for complex relationships","Karmasik iliskileri temsil eden dugum ve kenar yapisi","Model the social network as a graph.","Sosyal agi graf olarak modelleyin.","Sistem tasariminda",["directed graph — yonlu graf","graph traversal — graf gezinmesi"],"System design: 'Model connections as a graph.'","BFS ve DFS farkini bilmemek.",["node","edge","BFS","DFS"]))
terms.append(t("queue","Kuyruk","KYUU","intermediate","programming","A FIFO (First-In-First-Out) data structure","Ilk Giren Ilk Cikar veri yapisi","Add the task to the message queue.","Gorevi mesaj kuyruguna ekle.","Asenkron is islemede",["enqueue — kuyruga eklemek","dequeue — kuyruktan cikarmak"],"Architecture: 'Use a message queue for background jobs.'","Queue telaffuzunu yanlis yapmak.",["stack","FIFO","message queue"]))
terms.append(t("stack","Yigin","STAK","intermediate","programming","A LIFO (Last-In-First-Out) data structure","Son Giren Ilk Cikar veri yapisi","The call stack tracks function calls.","Cagri yigini fonksiyon cagrilarini takip eder.","JavaScript calisma mekanizmasinda",["push onto the stack — yigina itmek","pop from the stack — yigindan cikarmak"],"Mulakat: 'Implement a stack with getMin in O(1).'","Stack veri yapisi ile call stack karistirmak.",["queue","LIFO","call stack"]))
terms.append(t("heap","Obek","HIIP","advanced","programming","A tree-based data structure or dynamic memory region","Agac tabanli veri yapisi veya dinamik bellek bolgesi","Use a min-heap to find the smallest element.","En kucuk elemani bulmak icin min-heap kullan.","Algoritma optimizasyonunda",["heap allocation — heap tahsisi","min-heap / max-heap — min/maks heap"],"Mulakat: 'A heap is efficient for top K elements.'","Heap veri yapisi ile heap memory karistirmak.",["priority queue","binary tree","memory"]))
terms.append(t("binary search","Ikili arama","BAY-ni-ri SORC","intermediate","programming","A search algorithm dividing a sorted array in half","Sirali diziyi ikiye bolen arama algoritmasi","Binary search has O(log n) time complexity.","Ikili arama O(log n) karmasikligindadir.","Algoritma analizinde",["binary search on — uzerinde ikili arama"],"Mulakat: 'Array is sorted, use binary search.'","Sirali dizi gerektirdigini unutmak.",["sorting","divide and conquer","logarithmic"]))
terms.append(t("sorting","Siralama","SORT-ing","beginner","programming","Arranging elements in a specific order","Elemanlari belirli siraya dizme islemi","Which sorting algorithm is best here?","Hangi siralama algoritmasi en iyisi?","Performans tartismasinda",["sort by — gore siralamak","sort ascending — artan siralama"],"Mulakat: 'Compare merge sort vs quick sort.'","JavaScript sort() varsayilan string siralama yaptigini bilmemek.",["quick sort","merge sort","bubble sort"]))
terms.append(t("time complexity","Zaman karmasikligi","TAYM kim-PLEK-si-ti","intermediate","programming","How runtime grows relative to input size","Calisma suresinin girdi boyutuna gore buyumesi","What's the time complexity of your solution?","Cozumunun zaman karmasikligi ne?","Mulakat veya code review'da",["O(n) time complexity — O(n) zaman karmasikligi"],"Mulakat: 'Improve from O(n^2) to O(n log n).'","Best case ve worst case karistirmak.",["Big O","space complexity","algorithm"]))
terms.append(t("space complexity","Alan karmasikligi","SPEYS kim-PLEK-si-ti","intermediate","programming","How much memory an algorithm uses relative to input","Algoritmanin girdi boyutuna gore bellek kullanimi","Space complexity is O(n) because of the extra array.","Fazladan dizi nedeniyle alan karmasikligi O(n).","Algoritma analizinde",["O(1) space — sabit alan","in-place — yerinde"],"Mulakat: 'Solve it in-place for O(1) space.'","Sadece zaman karmasikligina odaklanmak.",["time complexity","memory","in-place"]))
terms.append(t("Big O notation","Buyuk O gosterimi","BIG O no-TEY-sin","intermediate","programming","Mathematical notation for algorithm growth rate upper bound","Algoritma buyume hizinin ust sinir gosterimi","This algorithm is O(n log n) in Big O.","Bu algoritma Big O'da O(n log n).","Algoritma tartisirken",["O(1) — sabit zaman","O(n) — dogrusal","O(n^2) — karesel"],"Mulakat: 'What's the Big O?'","O(n) ve O(2n) arasinda fark oldugunu sanmak.",["time complexity","space complexity","algorithm"]))
terms.append(t("memoization","Hafizaya alma","me-mo-i-ZEY-sin","advanced","programming","Caching results of expensive function calls","Pahali fonksiyon sonuclarini onbellege alma","Apply memoization to avoid redundant calculations.","Gereksiz hesaplamalar icin memoization uygula.","Performans optimizasyonunda",["memoize a function — fonksiyonu memoize etmek"],"Code review: 'Add memoization for performance.'","'Memoization' ile 'memorization' karistirmak.",["cache","dynamic programming","optimization"]))
terms.append(t("cache","Onbellek","KES","intermediate","programming","Temporary storage for frequently accessed data","Sik erisilen veriler icin gecici depolama","Cache the API response to reduce latency.","Gecikme azaltmak icin API yanitini onbellege al.","Performans iyilestirmesinde",["cache invalidation — onbellek gecersizlestirme","cache hit/miss — isabet/kacirma"],"Architecture: 'Add a caching layer.'","'Cache' telaffuzunu yanlis yapmak.",["Redis","CDN","memoization"]))
terms.append(t("middleware","Ara katman","MID-il-ver","intermediate","programming","Software acting as a bridge between components","Bilesenler arasi kopru gorevi goren yazilim","Add authentication middleware to protect routes.","Rotalari korumak icin auth middleware ekle.","Backend guvenliginde",["middleware function — middleware fonksiyonu","apply middleware — middleware uygulamak"],"Code review: 'Extract logging into middleware.'","Middleware sirasinin onemini bilmemek.",["express","interceptor","filter"]))

print(f"Programming: {len([x for x in terms if x['domain']=='programming'])}")

with open('/tmp/vocab_prog.json','w',encoding='utf-8') as f:
    json.dump(terms, f, ensure_ascii=False, indent=2)
print("Programming domain saved")
